Regular update '2022-08-03T17:56:01+00:00'

diff --git a/bin/pdftoimg b/bin/pdftoimg
--- a/bin/pdftoimg
+++ b/bin/pdftoimg
@@ -1,5 +1,12 @@
 #!/bin/bash
 
+echo ""
+echo ""
+echo "[ERROR] This script 'pdftoimg' has been deprecated. Please migrate to 'pdftopng'."
+echo ""
+echo ""
+exit 1
+
 IFFULLPATH="$1"
 IFNAME="$(basename "$IFFULLPATH")"
 OUTPUT_FORMAT="$2"
