Regular update '2022-08-25T18:48:59+00:00'

diff --git a/bin/repo-fastdeploy b/bin/repo-fastdeploy
--- a/bin/repo-fastdeploy
+++ b/bin/repo-fastdeploy
@@ -1,18 +1,22 @@
 #!/bin/bash
 
+if [[ "$HOSTNAME" != NDLT7 ]] && [[ "$FORCE" != y ]]; then
+    echo "[ERROR] This script may only be run on NDLT7."
+    exit 1
+fi
+
 DEFAULT_REMOTE_HOSTS=""
 source $HOME/.config/repo-fastdeploy.conf
 
 REMOTE_HOSTS="$DEFAULT_REMOTE_HOSTS"
 
-if [[ ! -z $1 ]]; then
-    ### Specify remotes in argv
+if [[ ! -z $1 ]]; then ### Specify remotes in argv
     REMOTE_HOSTS="$@"
 fi
 
 for host in $REMOTE_HOSTS; do
     if [[ ${host:0:1} != '#' ]]; then
         echo "[INFO] Deploying to '$host' ..."
-        rsync -a $PWD/ $host:$PWD/
+        rsync -apxm $PWD/ $host:$PWD/
     fi
 done
