Regular update '2022-12-12T02:05:09+00:00'

diff --git a/bin/saveFileToNasOSS b/bin/saveFileToNasOSS
--- a/bin/saveFileToNasOSS
+++ b/bin/saveFileToNasOSS
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+echo "[ERROR] Script saveFileToNasOSS is deprecated!"
+exit 1
+
 
 CONF=$HOME/.config/saveFileToNasOSS.conf
 if [[ -e $CONF ]]; then
