bin/tcrypt: v0.1.3

diff --git a/bin/tcrypt b/bin/tcrypt
--- a/bin/tcrypt
+++ b/bin/tcrypt
@@ -1,10 +1,10 @@
 #!/bin/bash
 
-APPVER="v0.1.2"
+APPVER="v0.1.3"
 
 function debug() {
     printf ""
-    echo "$1"
+    echo ">>> debug: $1"
 }
 
 CONFDIR="$HOME/.config/tcrypt"
@@ -29,6 +29,35 @@ fi
 PRIVKEYPATH="$CONFDIR/mykeys/$FULLNAME"
 
 
+
+
+
+
+
+
+### Library Functions
+function _addContact() {
+    echo "@name=$vSIGNER|@fp=$vFP|@sigkey=$vSIGKEY|@enckey=$vENCKEY" >> $CONFDIR/contacts.csv
+}
+function _getContactField() {
+MATCHTABLE="@lstpos=1,@fdname=name,@firstc=7
+@lstpos=2,@fdname=fp,@firstc=5
+@lstpos=3,@fdname=sigkey,@firstc=9
+@lstpos=4,@fdname=enckey,@firstc=9"
+    BY_FIELDNAME="$1"
+    BY_FIELDVAL="$2"
+    GET_FIELDNAME="$3"
+    MATCHED="$(echo "$MATCHTABLE" | grep "@fdname=$GET_FIELDNAME" | head -n1 )"
+    FIELD_POS="$(echo "$MATCHED" | cut -d',' -f1 | cut -b9-)"
+    FIRST_CHAR="$(echo "$MATCHED" | cut -d',' -f3 | cut -b9-)"
+    grep "@$BY_FIELDNAME=$BY_FIELDVAL" $CONFDIR/contacts.csv | head -n1 | cut -d'|' -f"$FIELD_POS" | cut -b"$FIRST_CHAR"-
+}
+
+
+
+
+
+
 function _help() {
 echo "tcrypt ($APPVER)
 
@@ -39,19 +68,21 @@ echo "tcrypt ($APPVER)
     https://github.com/neruthes/NDevShellRC/blob/master/bin/tcrypt
 
 
-SYNOPSIS:
-
+BASIC USAGE:
     tcrypt help                                     Print this help message.
-
     tcrypt keygen                                   Generate a keypair (ssh-ed25519).
+    tcrypt i|interpret                              Try interpreting a message from stdin.
+    tcrypt if|interpretfile FILE_PATH               Try interpreting a message from FIEL_PATH.
 
-    tcrypt clearsign                                Sign a clear text file from stdin.
+SIGNATURE:
+    tcrypt cs|clearsign                             Sign a clear text file from stdin.
+    tcrypt csf|clearsignfile FILE_PATH              Sign clear text file FILE_PATH.
+    tcrypt vcs|verifyclearsign                      Verify clearsign from stdin.
+    tcrypt vcsf|verifyclearsignfile FILE_PATH       Verify clearsign file FILE_PATH.
 
-    tcrypt clearsignfile FILE_PATH                  Sign clear text file FILE_PATH.
-
-    tcrypt verifyclearsign                          Verify clearsign from stdin.
-
-    tcrypt verifyclearsignfile FILE_PATH            Verify clearsign file FILE_PATH.
+DATA MANAGEMENT:
+    tcrypt ls|listcontacts                          Show the list of contacts.
+    tcrypt addcontactfromclearsign                  Read clearsign msg from stdin; add signer as contact.
 "
 }
 
@@ -113,6 +144,23 @@ case "$1" in
         cat "$PRIVKEYPATH".* > "$PRIVKEYPATH"
         ;;
 
+    i|interpret)
+        cat /dev/stdin > $TCryptSession.stdin
+        INITIAL_CHARS="$(head -n1 $TCryptSession.stdin)"
+        ### Decide which operation to execute
+        if [[ "$INITIAL_CHARS" == "#>MsgClearSig>"* ]]; then
+            $tcrypt vcs < $TCryptSession.stdin
+        fi
+        _clearSession
+        ;;
+
+    if|interpretfile)
+        INITIAL_CHARS="$(head -n1 "$2")"
+        ### Decide which operation to execute
+        if [[ "$INITIAL_CHARS" == "#>MsgClearSig>"* ]]; then
+            $tcrypt vcsf "$2"
+        fi
+        ;;
     cs|clearsign)
         _panicIfNoKeypair
         cat /dev/stdin > $TCryptSession.stdin
@@ -145,7 +193,7 @@ case "$1" in
         vFP="$(grep '#fingerprint=' $INPUTFN | cut -b14-)"
         vENCKEY="$(grep '#enckey=' $INPUTFN | cut -b9-)"
         if [[ "$(grep "$vSIGKEY" $CONFDIR/contacts.csv)" != '' ]]; then
-            echo "[ERROR] The public key '$vSIGKEY' is already a contact, known as '$(grep "$vSIGKEY" $CONFDIR/contacts.csv | head -n1 | cut -d'|' -f1)'."
+            echo "[ERROR] The public key '$vSIGKEY' is already a contact, known as '$(_getContactField sigkey "$vSIGKEY" name)'."
             echo "        Edit the file '$CONFDIR/contacts.csv' if you have worries."
             exit 1
         fi
@@ -154,9 +202,19 @@ case "$1" in
         echo "    Fingerprint:      $vFP"
         echo "    Signing Key:      $vSIGKEY"
         echo "    Encryption Key:   $vENCKEY"
-        # echo "    Name: $vSIGNER|$vSIGKEY|$vFP|$vENCKEY"
-        echo "$vSIGNER|$vSIGKEY|$vFP|$vENCKEY" >> $CONFDIR/contacts.csv
+        echo "@name=$vSIGNER|@fp=$vFP|@sigkey=$vSIGKEY|@enckey=$vENCKEY"
+        vSIGNER=$vSIGNER vFP=$vFP vSIGKEY=$vSIGKEY vENCKEY=$vENCKEY _addContact
+        # echo "@name=$vSIGNER|@fp=$vFP|@sigkey=$vSIGKEY|@enckey=$vENCKEY" >> $CONFDIR/contacts.csv
         _clearSession
+        ;;
+    ls|listcontacts)
+        echo "[INFO] List of contacts:" >&2
+            UUID="$(uuidgen v4)"
+            CONTACTS_LIST="$(cat $CONFDIR/contacts.csv | cut -d'|' -f1-1,3-3 --output-delimiter='   ')"
+            echo "$CONTACTS_LIST"
+            # IFS=$'\n' for line in $CONTACTS_LIST; do
+                # echo "  $line"
+            # done
         ;;
 
     ### Reserved for internal calls
@@ -227,9 +285,9 @@ case "$1" in
         if [[ "$VERIFY_RESULT" == 'Good "MsgSigV1" signature for'* ]]; then
             echo "[INFO] Signature from '$vSIGKEY' is valid."
             ### Can we find the SigKey in contacts?
-            if [[ "$(grep -v '^#' $CONFDIR/contacts.csv | grep "$vSIGKEY")" != "" ]]; then
+            if [[ "$(grep -v '^#' $CONFDIR/contacts.csv | grep "=$vSIGKEY")" != "" ]]; then
                 ### Found the sigkey
-                KEY_SAVED_NAME="$(grep "$vSIGKEY" $CONFDIR/contacts.csv | cut -d'|' -f1)"
+                KEY_SAVED_NAME="$(_getContactField sigkey "$vSIGKEY" name)"
                 CALCULATED_SAVED_FP="$($tcrypt u_calcSignerKeyFingerprint "$vSIGKEY")"
                 EXTRACTED_SAVED_FP="$(grep '#fingerprint=' $INPUTFN | cut -b14-)"
                 echo "[INFO] The signer is a contact, known as '$KEY_SAVED_NAME' (Fingerprint: $CALCULATED_SAVED_FP)."
@@ -242,7 +300,7 @@ case "$1" in
                 GREP_RESULT="$(grep "$vSIGKEY" $CONFDIR/known_signers.csv)"
                 if [[ "$GREP_RESULT" != "" ]]; then
                     MSG_COUNT="$(echo "$GREP_RESULT" | cut -d' ' -f4)"
-                    CACHED_NAME="$(echo "$GREP_RESULT" | cut -d' ' -f1)"
+                    CACHED_NAME="$(_getContactField sigkey "$vSIGKEY" name)"
                     echo "[INFO] We had verified $MSG_COUNT messages from this signer (previously known as '$CACHED_NAME') before."
                     ### Update the number
                     sed -i "s|$vSIGNER $vSIGKEY $MSG_COUNT|$vSIGNER $vSIGKEY $((MSG_COUNT+1))|" $CONFDIR/known_signers.csv
@@ -255,9 +313,8 @@ case "$1" in
         else
             echo "[FATAL] The signature is invalid!"
         fi
-
         printf "\n\n"
-        echo ""
+        _clearSession
         ;;
 
     *)
